### ISSUE TITLE
Some specific native attributes not applied in Shadow DOM

### ISSUE THREAD

**Issue by mcorbanini** [skatejs/skatejs#882]
I came up with this issue when I found a bug in a skatejs component that tried to set a string attribute named `value` inside the shadow DOM of another skatejs component
It works fine in Chrome but not in the rest of the browsers. The attribute seems to not have the value assigned but it is as an property.

I'm not sure why it is not working with this specific name, but I assume there is a reason and there should be more names that will have the same issues. The result, as you can see in the example, is an empty string. 
It's not the same case if you slot the component with the `value` attribute. That case it will work.

Open this example [here](http://codepen.io/mcorbanini/pen/VKgQxQ?editors=1010) in FF/Safari/ie
Skate version of the example is the latest.

Quick snippet to show the problem:
```javascript
// javascript
define('x-bar', {
  props: {
    value: prop.string({ attribute: true }),
  }
});
define('x-foo', {
  render() {
    return (
      vdom.element('div', () => {
        vdom.element('x-bar', { value: 'b'})   // this won't work
        vdom.element('slot')
      })
    );
  },
});

// html
<x-foo>
  <x-bar value="1"/>    // this will work
</x-foo>
```

You end up having something like this in FF:

<img width="285" alt="screen shot 2016-10-24 at 6 01 37 pm" src="https://cloud.githubusercontent.com/assets/763532/19636252/eb3a149e-9a13-11e6-9c1f-373f2e1905db.png">

**Comment by treshugart** [comment]
@mcorbanini can you retest with 4.0.1? I think this was fixed in #876.

**Comment by mcorbanini** [comment]
No, it was not fixed. Same issue happening [here](http://codepen.io/mcorbanini/pen/VKgQxQ) if you open it in FF.

**Comment by mcorbanini** [comment]
Since this is not a critical bug and we are not sure if it's related with skate or not I'm closing this issue.
It's only happening in FF but not in other browsers without native support like ie
It can easily be solved by changing the attribute to a different name for now.
